### ISSUE TITLE
weakly-supervised methods learning error

### ISSUE THREAD

**Issue by pjs22** [xuhongzuo/DeepOD#25]
When using the code below
"
from deepod.models.devnet import DevNet
clf = DevNet()
clf.fit(X_train, y=semi_y) # semi_y uses 1 for known anomalies, and 0 for unlabeled data
"
At this part
"clf.fit(X_train, y=semi_y)"

"Float division by zero" error occurs 

How can I resolve the above error?
I put a two-dimensional array in the "x_train" variable, and a list of zeroes in the "y" variable because they are all normal data.

**Comment by xuhongzuo** [comment]
DevNet is a weakly supervised model that uses partially labeled anomalies, please see its  original paper for more detail. therefore, if your input contains normal data only, it cannot work properly.



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/10/2023 22:14 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [xuhongzuo/DeepOD] weakly-supervised methods learning error (Issue #25) |

When using the code below
"
from deepod.models.devnet import DevNet
clf = DevNet()
clf.fit(X_train, y=semi_y) # semi_y uses 1 for known anomalies, and 0 for unlabeled data
"
At this part
"clf.fit(X_train, y=semi_y)"

"Float division by zero" error occurs

How can I resolve the above error?
I put a two-dimensional array in the "x_train" variable, and a list of zeroes in the "y" variable because they are all normal data.

**Comment by pjs22** [comment]
I tried putting the label in both 0,1, but the same error occurs.

**Comment by xuhongzuo** [comment]
Please check your input X_train, is there a all-zero feature? We do not add strict input check in DeepOD. 
DevNet passed my test (you can see testing script in deepod/test/test_devnet.py). 



| |
Hongzuo Xu
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 8/10/2023 22:58 |
| To | ***@***.***> |
| Cc | Hongzuo ***@***.***> ,
***@***.***> |
| Subject | Re: [xuhongzuo/DeepOD] weakly-supervised methods learning error (Issue #25) |

I tried putting the label in both 0,1, but the same error occurs.
